### ISSUE TITLE
Create Statement of Administrative Policy section on Bills page - UI Changes

### ISSUE THREAD

**Issue by ayeshamk** [aih/FlatGov#132]

**Comment by aih** [comment]
I've pulled cc7e6c6821d5bcc2ea23dcd from `FT_branch_1`, I created a database migration from the models (`python manage.py makemigration`) and pushed that to the branch.

Now I'm running the server and do not see the table for bills I would expect:

116hjres7 (also tested 115hjres7):
![image](https://user-images.githubusercontent.com/217356/105774876-b4ada780-5f1a-11eb-93ec-32ada6643e51.png)

116hr7617:
![image](https://user-images.githubusercontent.com/217356/105775039-fb030680-5f1a-11eb-8fd0-5231ee5ecd7b.png)

**Comment by aih** [comment]
@ayeshamk, I recommend the following:

- [ ] Store the pdfs in directories by either year or Congress number. Alternately, start the pdf name with the congressnumber, e.g. 116-HR123.pdf. They pdfs are all currently in `Flatgov/media/statements/Trump`. Since one President overlaps more than one Congress, this structure will cause a collision at some point.

- [ ]  There may be a missing step to populate the Statements in the database. Please document how I should do that for testing and deployment.

- [ ]  Please include a screenshot in this issue of a bill with the table working, so I can know which to test.
