### ISSUE TITLE
Include short title (or truncated short title) in typeahead search list

### ISSUE THREAD

**Issue by nkinaba** [aih/FlatGov#273]
1. Display search results in H.R. XXX format
<img width="393" alt="Screen Shot 2021-03-31 at 3 00 24 PM" src="https://user-images.githubusercontent.com/69855502/113196735-d33d6100-9231-11eb-95cc-f2f45b3a21f1.png">

2. Search results should include short bill title or title up to x amount of characters included in the search result so users have more information and can identify which bill they’re looking for or want to learn more about  
Ex:    
H.R. 736 Access to Congressionally Mandated Reports Act

**Comment by aih** [comment]
Added views to return a list of [billnumber, short title] pairs for each congress. Note that many pairs have 'null' for the Short Title, so that will need to be handled.

http://localhost:8000/home/bill-st-list/115
![image](https://user-images.githubusercontent.com/217356/113832018-0e152c80-973d-11eb-8da2-629a18c17877.png)
